- components/Form/Form.js
- package-lock.json
- package.json
- server.js
- services/sendMail.js
Nodemailer para mandar mails desde /contact
> Node mailer

- next.config.js
- pages/users.js
Se creo una nuevo archivo en la carpeta `pages` llamado `users.js` y se agrego el export de la misma a `next.config.js`.
> Crear nueva page /users (BILW-021)

- .github/CODEOWNERS
- next.config.js
> Add GitHub config folder

- components/Menu/Desktop.js
- components/Menu/Mobile.js
- next.config.js
- pages/users.js
- pages/utils.js
Added to the page /users the DownloadUtils component. 
Deleted the page /utils and both Links off Desktop and Mobile Menu.
> Add Download Utils to /users (BILW-007)

- next.config.js
- pages/faqs.js
Added the page /faqs and the route for it in next.config.js
> Crear sub-sección/vista "FAQs" (BILW-003)

- mocks/general.js
- pages/versions-detail.js
Add features to details page:
- Administration module
- Audit module
- OSDE module
> Add features to details

- mocks/faqs.js
- package-lock.json
Created a JSON object that exports an array of questions and answers.
> Create a JSON structure with the information (questions and answers) with which it will be fed this view (BILW-008)

- mocks/general.js
- next.config.js
- pages/versions-detail.js
Revert changes in develop
- Users link
- Version details modules
> Revert menu utils link

- next.config.js
Se creo la nueva sub seccion/vista Documentacion para que dentro de la seccion "Usuarios", se pueda acceder a ella.
> Se creo sub-sección/vista "Documentación"

- components/Docs/Docs.js
- components/Docs/DocsWrapper.js
- components/Docs/Item.js
- components/Docs/Sidebar.js
- components/Docs/content.js
- contents/documentation/content.js
- contents/documentation/sidebar.js
- contexts/docContext.js
- mocks/cardUserData.js
- next.config.js
* Agregando la sub-seccion/vista llamada docuemntacion dentro de la seccion usuarios
* Creacion de la pagina docs.js en la cual se crea un estructura JSON con informacion sobre Bilow Software y sus caracteristicas mas sobresalientes
* Correccion de algunos errores de tipeo en la seccion category/urlHash
* Se agrego a cada featureContent de este archivo el item video con su respectivo valor
* Se agrego el titulo Sistema en el featureContent users
* Cambios en la ruta de la subseccion/vista docuemnts
* Modificaciones en el next.config.js. Cambios en la ruta /document
* Creacion del componente NavDoc
* feat: create documentation page and content
* feat: create documentation content and view
* fix: fine tunning
Co-authored-by: Rodrigo Juarez <juarezrodrigo59@gmail.com>
Co-authored-by: …
> Create documentation content and view (#40)

- static/emails/bilog-encuesta.html
> Create encuesta mailing

- components/Testimonials/Badge.js
- components/Testimonials/index.js
- mocks/cardUserData.js
- mocks/testimonials.js
- pages/testimonials.js
Created the components Testimonials(index)  and Badge.
Applied styles to both of them.
> Created a component Badge that consumes the JSON and allows to display the different testimonials (BILW-017)

- mocks/odontologicaMock.js
- pages/odontologica.js
Components Cover now receive the props from this new JSON structure.
> Designed the JSON structure for the page odontologica. (BILW-018)

- components/Layout.js
- config/index.js
- Move tracking config to /config
- Add GTM for www.bilog.cl
> Add gtm for chile

- static/emails/bilog-app.html
Este newsletter describe e informa las caracteristicas y funcionalidades de Bilog App. Aqui debajo se podra visualizar la vista previa. 👇
> Creacion del newswletter bilog-app (BILW-028)

- static/emails/bilog-lanzamiento-tres.html
Vista previa en Desktop. 👇🖥
Vista previa en Mobile 👇📱
> Newsletter informativo de Bilog App (BILW-043)

- static/emails/bilog-lanzamiento-dos.html
Esta es la vista previa del newsletter en la version desktop. 👇
Esta es la vista previa del newsletter en la version mobile. 👇
> Newsletter dedicado al lanzamiento de la App de Bilog. (BILW-042)

- mocks/general.js
Vista previa de las modificaciones en el footer
> Modifications in the support section of the footer (BILW-047)

- static/emails/bilog-lanzamiento-cuatro.html
Vista previa en version desktop 
Vista previa en version mobile
> Newsletter de lanzamiento de Bilog App (BILW-044)

- next.config.js
- pages/demo.js
> New demo page (BILW-050)

- components/Accordion/Accordion.js
- components/Docs/SidebarSection.js
- components/Docs/sidebar/desktop.js
- components/Docs/sidebar/mobile.js
- components/Docs/sidebar/submenu.js
- contents/documentation/sidebar.js
- contexts/docContext.js
Styles from desktop. 
Styles from mobile
> Creation of the accordion component and adjustments of the styles in mobile and desktop (BILW-049)

- pages/demo.js
Replicate component <Features /> found in /odontologica.
Desktop
Mobile
>  Replicate component <Features /> found in / odontologica

- pages/demo.js
> Carousel on the demo page

- components/Cover/Cover.js
- mocks/landingMock.js
- mocks/promotionsMock.js
- pages/auditoria.js
- pages/bilogApp.js
- pages/index.js
- pages/promotions.js
Está subido en http://test.bilog.com.ar/
> feat: create cover for hot week
